# Generated by Django 5.0.6 on 2024-06-16 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('patientId', models.CharField(max_length=100, unique=True)),
                ('doctorName', models.CharField(max_length=100)),
                ('appointmentDate', models.DateField(default=django.utils.timezone.now)),
                ('appointmentTime', models.TimeField(default=django.utils.timezone.now)),
                ('heartRate', models.CharField(max_length=20)),
                ('diastolicBP', models.CharField(max_length=20)),
                ('systolicBP', models.CharField(max_length=20)),
                ('bodyTemp', models.CharField(max_length=20)),
                ('spo2Value', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
