import React from 'react';
import img from './../assets/logo.png';

const Footer = () => {
  return (
    <footer className="bg-gray-800 text-gray-300 py-4">
      <div className="mx-auto px-4 md:px-8 flex flex-col md:flex-row items-center justify-between">
        <div className="flex flex-col md:flex-row items-center gap-2">
          <img src={img} alt="logo" className="w-auto h-8 border-1 rounded" />
          <div className="flex flex-col gap-2 md:gap-5">
            <span className="text-xl font-bold">Charak Centre IIT Indore</span>
            <span className="text-sm">©2024 Charak Centre IIT Indore. All rights reserved</span>
            <div className='flex flex-col md:flex-row gap-2'>
              <span className='font-bold text-slate-400'>Disclaimer:</span>
              <span className='text-slate-500'>This software is under development. Please consult with a doctor before acting on any decisions/interface generated by this tool.</span>
            </div>
          </div>
        </div>

        <div className="flex flex-col md:flex-row space-y-2 md:space-y-0 space-x-0 md:space-x-5 mt-4 md:mt-0">
          <a href="https://charakcenter.iiti.ac.in" className="hover:text-white text-sm">About</a>
          <a href="#" className="hover:text-white text-sm">Contact</a>
          <a href="#" className="hover:text-white text-sm">Privacy Policy</a>
          <a href="#" className="hover:text-white text-sm">Terms of Service</a>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
